[project]
name = "minigridmp-aif-jax"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gymnasium>=1.2.3",
    "imageio>=2.37.2",
    "imageio-ffmpeg>=0.6.0",
    "jax>=0.6.2",
    "matplotlib>=3.10.8",
    "minigrid>=3.0.0",
    "pytest>=9.0.2",
    "tqdm>=4.67.3",
]

[tool.setuptools.packages.find]
include = ["agents*", "environments*", "inference*", "utils*"]

[dependency-groups]
dev = ["dvc>=3.56"]
cuda = [
    "jax[cuda12-pip]>=0.9.0",
]
macos = ["jax-mps>=0.9.6"]
