#!/usr/bin/env python
"""Deterioration sweep: measure success rate vs observation noise for multiple methods."""

import sys
from pathlib import Path
import argparse
import json
import time
import random

sys.path.insert(0, str(Path(__file__).parent))

import numpy as np
import yaml
import jax
import jax.numpy as jnp
from environments.minigrid import (
    generate_transition_tensor,
    generate_observation_tensor,
    generate_orientation_observation_tensor,
    soften_observation_tensor,
)
from environments.gym_wrapper import run_experiment
from agents.flat_tensor_agent import (
    IndexedTensorAgent, VBPAgent, LoopyVBPAgent, LoopyBPAgent,
    RegionExtendedAgent, ReducedRegionExtendedAgent,
    DynChannelLoopyBPAgent, ReducedDynChannelAgent,
    NuijtenMPAgent, ReducedNuijtenMPAgent,
)
from utils.tensors import get_dimensions, flatten_state_index


def create_goal_distribution(grid_size, goal_x, goal_y):
    dims = get_dimensions(grid_size)
    goal = jnp.zeros(dims["n_states"])
    goal_location = goal_x * grid_size + goal_y
    for orientation in range(dims["n_orientations"]):
        idx = flatten_state_index(
            goal_location, orientation, 2,
            dims["n_locations"], dims["n_orientations"], dims["n_door_key_states"],
        )
        goal = goal.at[idx].set(1.0)
    return goal / goal.sum()


def create_agent(method, grid_size, transition_tensor, observation_tensor,
                 orientation_tensor, goal, planning_horizon,
                 inference_iterations, planning_iterations, damping):
    common = dict(
        grid_size=grid_size,
        observation_tensors=observation_tensor,
        orientation_tensor=orientation_tensor,
        goal=goal,
        planning_horizon=planning_horizon,
        n_inference_iterations=inference_iterations,
        n_planning_iterations=planning_iterations,
    )
    damping_agents = {"region-extended", "reduced-aif", "dyn-channel", "reduced-dyn-channel"}
    extra = dict(damping=damping) if method in damping_agents else {}

    agent_map = {
        "bp": IndexedTensorAgent,
        "vbp": VBPAgent,
        "loopy-vbp": LoopyVBPAgent,
        "loopy": LoopyBPAgent,
        "region-extended": RegionExtendedAgent,
        "reduced-aif": ReducedRegionExtendedAgent,
        "dyn-channel": DynChannelLoopyBPAgent,
        "reduced-dyn-channel": ReducedDynChannelAgent,
        "nuijten": NuijtenMPAgent,
        "reduced-nuijten": ReducedNuijtenMPAgent,
    }
    cls = agent_map.get(method, IndexedTensorAgent)
    return cls.create(transition_tensor=transition_tensor, **common, **extra)


def generate_tikz(all_results, config):
    """Generate a standalone pgfplots .tex file with deterioration curves."""
    marks = ["*", "square*", "triangle*", "star", "diamond*",
             "otimes*", "pentagon*", "halfsquare*"]
    colors = ["blue", "red", "green!60!black", "orange", "purple",
              "cyan", "brown", "magenta"]

    plots = []
    legend_entries = []
    for i, (method, data) in enumerate(all_results.items()):
        mark = marks[i % len(marks)]
        color = colors[i % len(colors)]
        coords = "\n".join(
            f"    ({r['alpha']}, {r['success_rate']:.4f})"
            for r in data["results"]
        )
        plots.append(
            f"\\addplot[mark={mark}, {color}, thick] coordinates {{\n{coords}\n}};"
        )
        legend_entries.append(method)

    legend = ", ".join(legend_entries)
    grid_size = config["grid_size"]
    horizon = config["planning_horizon"]

    return f"""\
% Auto-generated by run_deterioration.py
\\documentclass[tikz]{{standalone}}
\\usepackage{{pgfplots}}
\\pgfplotsset{{compat=1.18}}
\\begin{{document}}
\\begin{{tikzpicture}}
\\begin{{axis}}[
    xlabel={{Observation noise $\\alpha$}},
    ylabel={{Success probability}},
    title={{Deterioration (grid={grid_size}, T={horizon})}},
    grid=major,
    mark size=2pt,
    legend pos=north east,
    legend entries={{{legend}}},
    ymin=0, ymax=1.05,
]
{chr(10).join(plots)}
\\end{{axis}}
\\end{{tikzpicture}}
\\end{{document}}
"""


def main():
    parser = argparse.ArgumentParser(
        description="Deterioration sweep: success rate vs observation noise")
    parser.add_argument("--grid-size", type=int, default=None)
    parser.add_argument("--fov-size", type=int, default=None)
    parser.add_argument("--damping", type=float, default=None)
    parser.add_argument("--seed", type=int, default=None)
    parser.add_argument("--episodes", type=int, default=None)
    parser.add_argument("--max-steps", type=int, default=None)
    parser.add_argument("--planning-horizon", type=int, default=None)
    parser.add_argument("--inference-iterations", type=int, default=None)
    parser.add_argument("--receding-horizon", action="store_true")
    parser.add_argument("--no-orientation", action="store_true")
    parser.add_argument("--output-dir", type=str, default="data/deterioration")
    args = parser.parse_args()

    # Load params.yaml
    with open("params.yaml") as f:
        params = yaml.safe_load(f)

    det = params["deterioration"]
    det_methods = params["deterioration_methods"]
    exp = params["experiment"]

    # CLI overrides or params.yaml defaults
    grid_size = args.grid_size or exp["grid_size"]
    fov_size = args.fov_size or exp["fov_size"]
    damping = args.damping if args.damping is not None else exp["damping"]
    seed = args.seed if args.seed is not None else det["seed"]
    episodes = args.episodes or det["episodes"]
    max_steps = args.max_steps or det["max_steps"]
    planning_horizon = args.planning_horizon or det["planning_horizon"]
    inference_iterations = args.inference_iterations or det["inference_iterations"]
    alphas = det["alphas"]

    minigrid_size = grid_size + 2
    env_name = f"MiniGrid-DoorKey-{minigrid_size}x{minigrid_size}-v0"

    print(f"JAX devices: {jax.devices()}")
    print(f"Grid: {grid_size}x{grid_size}  Horizon: {planning_horizon}")
    print(f"Episodes: {episodes}  Max steps: {max_steps}")
    print(f"Alphas: {alphas}")
    print(f"Methods: {list(det_methods.keys())}")
    print()

    # Generate tensors (transition is shared, obs generated per alpha)
    print("Generating transition tensor...")
    t0 = time.time()
    transition_tensor = jnp.array(generate_transition_tensor(grid_size), dtype=jnp.float32)
    orientation_tensor = jnp.array(
        generate_orientation_observation_tensor(grid_size), dtype=jnp.float32)
    base_obs_np = generate_observation_tensor(grid_size, fov_size=fov_size)
    print(f"  Done in {time.time() - t0:.2f}s")
    print()

    goal_x = grid_size - 1
    goal_y = 0
    goal = create_goal_distribution(grid_size, goal_x, goal_y)

    # Sweep
    all_results = {}
    for method, method_cfg in det_methods.items():
        planning_iterations = method_cfg["planning_iterations"]
        print(f"=== Method: {method} (planning_iterations={planning_iterations}) ===")
        method_results = []

        for alpha in alphas:
            random.seed(seed)
            np.random.seed(seed)

            # Soften observation tensor for this alpha
            if alpha > 0.0:
                obs_np = soften_observation_tensor(base_obs_np, fov_size, alpha)
            else:
                obs_np = base_obs_np
            observation_tensor = jnp.array(obs_np, dtype=jnp.float32)

            agent = create_agent(
                method, grid_size, transition_tensor, observation_tensor,
                orientation_tensor, goal, planning_horizon,
                inference_iterations, planning_iterations, damping,
            )

            t0 = time.time()
            results = run_experiment(
                agent=agent,
                env_name=env_name,
                n_episodes=episodes,
                max_steps=max_steps,
                receding_horizon=args.receding_horizon,
                seed_start=seed,
                verbose=False,
                show_progress=True,
                fov_size=fov_size,
                no_orientation=args.no_orientation,
                obs_alpha=alpha,
            )
            elapsed = time.time() - t0

            entry = {
                "alpha": alpha,
                "success_rate": results["success_rate"],
                "avg_steps": results["avg_steps"],
                "avg_reward": results["avg_reward"],
            }
            method_results.append(entry)
            print(f"  alpha={alpha:.2f}: success={results['success_rate']:.1%}  "
                  f"steps={results['avg_steps']:.1f}  ({elapsed:.1f}s)")

        all_results[method] = {
            "planning_iterations": planning_iterations,
            "results": method_results,
        }
        print()

    # Save outputs
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    config = {
        "grid_size": grid_size,
        "fov_size": fov_size,
        "damping": damping,
        "episodes": episodes,
        "max_steps": max_steps,
        "planning_horizon": planning_horizon,
        "inference_iterations": inference_iterations,
        "seed": seed,
        "alphas": alphas,
    }

    # JSON
    json_path = output_dir / "results.json"
    with open(json_path, "w") as f:
        json.dump({"config": config, "methods": all_results}, f, indent=2)
    print(f"Results saved to {json_path}")

    # TikZ
    tex_path = output_dir / "deterioration.tex"
    tex_path.write_text(generate_tikz(all_results, config))
    print(f"TikZ saved to {tex_path}")

    # Matplotlib PNG
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        markers = ["o", "s", "^", "*", "D", "v", "p", "h"]
        fig, ax = plt.subplots(figsize=(8, 5))

        for i, (method, data) in enumerate(all_results.items()):
            xs = [r["alpha"] for r in data["results"]]
            ys = [r["success_rate"] for r in data["results"]]
            marker = markers[i % len(markers)]
            ax.plot(xs, ys, f"{marker}-", label=method, markersize=6)

        ax.set_xlabel("Observation noise α")
        ax.set_ylabel("Success probability")
        ax.set_title(
            f"Deterioration (grid={grid_size}, T={planning_horizon})"
        )
        ax.set_ylim(-0.05, 1.05)
        ax.legend(loc="upper right")
        ax.grid(True, alpha=0.3)
        fig.tight_layout()

        png_path = output_dir / "deterioration.png"
        fig.savefig(png_path, dpi=150)
        plt.close(fig)
        print(f"PNG saved to {png_path}")
    except ImportError:
        print("matplotlib not available — skipping PNG")


if __name__ == "__main__":
    main()
